# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2


class CommonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.handle = channel.unary_unary(
                '/common.CommonService/handle',
                request_serializer=common__pb2.CommonRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )


class CommonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def handle(self, request, context):
        """基础Demo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'handle': grpc.unary_unary_rpc_method_handler(
                    servicer.handle,
                    request_deserializer=common__pb2.CommonRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'common.CommonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def handle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/common.CommonService/handle',
            common__pb2.CommonRequest.SerializeToString,
            common__pb2.CommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
