/**
 * @fileoverview gRPC-Web generated client stub for common
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.4
// source: common.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.common = require('./common_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.common.CommonServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.common.CommonServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.common.CommonRequest,
 *   !proto.common.CommonResponse>}
 */
const methodDescriptor_CommonService_handle = new grpc.web.MethodDescriptor(
  '/common.CommonService/handle',
  grpc.web.MethodType.UNARY,
  proto.common.CommonRequest,
  proto.common.CommonResponse,
  /**
   * @param {!proto.common.CommonRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.common.CommonResponse.deserializeBinary
);


/**
 * @param {!proto.common.CommonRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.common.CommonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.common.CommonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.common.CommonServiceClient.prototype.handle =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/common.CommonService/handle',
      request,
      metadata || {},
      methodDescriptor_CommonService_handle,
      callback);
};


/**
 * @param {!proto.common.CommonRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.common.CommonResponse>}
 *     Promise that resolves to the response
 */
proto.common.CommonServicePromiseClient.prototype.handle =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/common.CommonService/handle',
      request,
      metadata || {},
      methodDescriptor_CommonService_handle);
};


module.exports = proto.common;

