# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"1\n\x0b\x45\x63hoRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x13\n\x0b\x65xtra_times\x18\x02 \x01(\r\"\x1e\n\x0c\x45\x63hoResponse\x12\x0e\n\x06values\x18\x01 \x03(\t\"#\n\x12\x45\x63hoStreamResponse\x12\r\n\x05value\x18\x01 \x01(\t2r\n\x04\x45\x63ho\x12-\n\x04\x45\x63ho\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponse\x12;\n\nEchoStream\x12\x11.echo.EchoRequest\x1a\x18.echo.EchoStreamResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ECHOREQUEST._serialized_start=20
  _ECHOREQUEST._serialized_end=69
  _ECHORESPONSE._serialized_start=71
  _ECHORESPONSE._serialized_end=101
  _ECHOSTREAMRESPONSE._serialized_start=103
  _ECHOSTREAMRESPONSE._serialized_end=138
  _ECHO._serialized_start=140
  _ECHO._serialized_end=254
# @@protoc_insertion_point(module_scope)
